### PR TITLE
Beaker jobs should be canceled if Jenkins job fails/canceled by user

### PR DESCRIPTION
**Pull request by stowellm**
As discussed in issue #10, here is a proposed solution.  It is like a "teardown" step that other CI frameworks use.

### CODE REVIEW

**Comment by lulinqing** [comment]
That's a good think to release beaker resource once a test is no longer required. Thanks Mike!
Currently people need to cancel them in beaker or in a [dedicated job](https://platform-stg-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kernel-general-zstream-cancel/build).

A few things to be considered in this case:
- [ ] people are getting their bkr_job.txt from different commands in their job YAMLs, thus the fixed command in template YAML for interpreting $BKR_ID may or may not work for all of them. Can we improve this part a little (e.g. inject env var, to pass beaker job IDs in consistent format from job shell) to avoid this potential issue?
- [ ] Should we limit the postbuild script to be triggered only for "canceled" jobs? "failed" ones are usually caused by infra issues like network problem (failed beaker tasks should not fail the jenkins job, plus they are already finished so no need to cancel again) - thus people may expect the important tests to continue on beaker instead of being interrupted (that's also the reason why we use beaker heavily in MVP).
- [ ] minor format update for indentation - jjb failed before a few more blanks inserted accordingly

**Comment by stowellm** [comment]
Thanks for the review.  To each of your comments, respectively:
- Good point.  I copied the syntax to get the BKR_JOBID from the `sample_job.yaml`, but it would be better if we added an inject step to avoid the user needing to change this in both files.  I will add this.
- From the [documentation on postbuildscript](http://docs.openstack.org/infra/jenkins-job-builder/publishers.html?highlight=script-only-if#publishers.postbuildscript), it looks like we can only trigger it on success/failure, where "failure" broadly includes Jenkins job failing, aborting, and cancelling.  Perhaps Jenkins sends a specific signal on cancelled jobs as opposed to other "failed" jobs that we can trap and run the `bkr job-cancel` there .. I will look into this.  If its as simple as something like:  
  `trap "echo 'Cancel received - cleaning Beaker jobs'; bkr job-cancel $BKR_JOBID; exit 1" SIGHUP SIGINT SIGTERM`  
  , then we wouldn't even need the postbuildscript 
- Good catch - fixed it

**Comment by vhumpa** [comment]
This (postbuildscript) is exactly what we do in our Jenkins. Basically, by the time the beaker job finishes (even by FAIL/ABORT), we are always still on successful build status, so at the time the first postbuildscript runs, fails are only caused by cancelling jobs, or other jenkins/harness related failures - when we usually don't have a beaker job, so the bkr job-cancel does nothing. IMO, no need to trap cancels. If we would want to do so though, Jenkins spits "Build was aborted" in console, which can be searched for in a groovy post script, i.e. something like:

```
      - groovy-postbuild:
          script: |
              def matcher = manager.getLogMatcher(".*Build was aborted.*")
              if(matcher?.matches()) {{
                  def process = ["sh", "-c", "bkr", "job-cancel", "`cat beaker_job_id`"].execute()
                  println process.text
              }} 
```

**Comment by stowellm** [comment]
@lulinqing, what do you think of using a groovy-postbuild such as that suggested by @vhumpa?  We could combine this with an env inject step so we'd have something like the following in the sample job yaml:
- submit the Beaker jobs and save to BKR_JOBID
- add env inject step to save BKR_JOBID as env variable
- add another shell to continue the job watching/results formatting after the env inject

If we do go this route using Groovy, you may need to enable some scripts on Jenkins, as we get this error:

```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method java.util.regex.Matcher matches
```

**Comment by vhumpa** [comment]
@stowellm Perhaps simply adding the groovy-postbuild as another step (to always run after the job-watch finishes) should be sufficient, without the need of splitting the current 'shell' step. Either:
- Job has completed and a job-watch task in the build 'shell' has finished, groovy code does not find the 'aborted' message and does nothing.
- Job got cancelled, 'shell' job-watch gets interrupted, groovy code finds the abort message and submits the job-cancel request.

As to the job ID transfer, injection is one possibility - but since the var inject step requires that to be stored in a property file, we might as well store the id in a file directly to 'cat' it later whenever needed, like in the previous groovy example.

**Comment by stowellm** [comment]
I've updated the pull request to include the env-inject step.  Commit 3837048 is wrongly titled with "groovy postbuild" as I did not include that yet (and rather avoid rewriting Git history so .. leaving it with an incorrect title).  This works fine on PJM, but again, does not address the comment @lulinqing made:

```
Should we limit the postbuild script to be triggered only for "canceled" jobs? "failed" ones are usually caused by infra issues like network problem (failed beaker tasks should not fail the jenkins job, plus they are already finished so no need to cancel again) - thus people may expect the important tests to continue on beaker instead of being interrupted (that's also the reason why we use beaker heavily in MVP).
```

, but does address the other issues.  I did not find an alternative that can accomplish this (i.e. detecting canceled jobs) without Groovy, and as noted in one of my above comments, Groovy requires some script access permissions.

@vhumpa, we could store the job ID in a file, but then we'd need to archive it anyways.  That seems to be the purpose of using env inject, so why avoid using it.

Anyways, not sure how to proceed.  If we do decide we need Groovy (or another alternative to address the comment currently unaddressed), then I invite someone to provide such code.

**Comment by lulinqing** [comment]
Current version looks good to me - had a quick test and worked fine (job/kernel-general-rhel-kabi/111).
We'll merge it in a week if no objection, and more feedback from folks would be appreciated.

**Pull request merged**
